name: Deploy to WordPress SVN

on:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2

      - name: Setup SVN
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Checkout WordPress SVN repo
        run: |
          svn checkout --username ${{ secrets.SVN_USERNAME }} --password="${{ secrets.SVN_PASSWORD }}" https://plugins.svn.wordpress.org/pagbank-connect/ ./svn --no-auth-cache
        shell: bash -O extglob {0}
        
      - name: Copy files
        run: |
          rsync -r --filter='merge .github/workflows/.rsync-filter' ./ ./svn/trunk/

      - name: Commit and push to WordPress SVN
        run: |
          cd ./svn/trunk/
          svn add --force * --auto-props --parents --depth infinity -q
          svn ci -m "Deploying version ${{ github.ref }} from GitHub." --password="${{ secrets.SVN_PASSWORD }}"